import AppProvider from "@/components/AppContext";
import "./globals.css";
import Header from "@/components/layout/Header";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <AppProvider>
      <Toaster />
      <Header />
        {children}
        <footer className="border-t p-8 text-center text-gray-500 mt-16">
              &copy; 2024 All rights reserved
        </footer>
      </AppProvider>
      </body>
    </html>
  );
}
